从2.9.4兼容到go1.11.13版本

diff --git a/.github/workflows/format-code-on-push.yml b/.github/workflows/format-code-on-push.yml
--- a/.github/workflows/format-code-on-push.yml
+++ b/.github/workflows/format-code-on-push.yml
@@ -1,14 +1,14 @@
-name: Format Code on Push
+name: Format Code Check
 
 on:
   push
 
 jobs:
-  format-code:
+  format-code-check:
     strategy:
       matrix:
         go-version: [ 'stable' ]
-    name: format-code-by-gci
+    name: check-code-format-by-gci
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -18,44 +18,14 @@ jobs:
         with:
           go-version: ${{ matrix.go-version }}
       - name: Install gci
-        run: go install github.com/daixiang0/gci@latest
-      - name: Run gci
-        run: |
-          gci write --custom-order \
-          --skip-generated \
-          --skip-vendor \
-          -s standard \
-          -s blank \
-          -s default \
-          -s dot \
-          -s "prefix(github.com/gogf/gf/v2)" \
-          -s "prefix(github.com/gogf/gf/cmd)" \
-          -s "prefix(github.com/gogf/gf/contrib)" \
-          -s "prefix(github.com/gogf/gf/example)" \
-          ./
-      - name: Check for changes
+        run: go install github.com/daixiang0/gci@v0.14.0
+      - name: Check code format by gci
+        run: gci write --custom-order --skip-generated --skip-vendor -s standard -s blank -s default -s dot -s "prefix(github.com/gogf/gf/v2)" -s "prefix(github.com/gogf/gf/cmd)" -s "prefix(github.com/gogf/gf/contrib)" -s "prefix(github.com/gogf/gf/example)" ./
+      - name: Report status
         run: |
           if [[ -n "$(git status --porcelain)" ]]; then
-            echo "HAS_CHANGES=true" >> $GITHUB_ENV
+            echo "::error::Code format check failed. Please run gci locally and commit the changes."
+            exit 1
           else
-            echo "HAS_CHANGES=false" >> $GITHUB_ENV
-          fi         
-      - name: Configure Git
-        run: |
-          if [[ "$HAS_CHANGES" == 'true' ]]; then
-            git config --global user.name "github-actions[bot]"
-            git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          else
-            echo "HAS_CHANGES= $HAS_CHANGES "
+            echo "Code format check passed."
           fi
-      - name: Commit and push changes
-        run: |
-          if [[ "$HAS_CHANGES" == 'true' ]]; then
-            git add .
-            git commit -m "Apply gci import order changes"
-            git push origin ${{ github.event.pull_request.head.ref }}
-          else
-            echo "No change to commit push"
-          fi
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
